import json
import logging
from datetime import datetime
import requests

logger = logging.getLogger(__name__)

class ReportGenerator:
    def create_report(self, cluster_data, analysis):
        """Create formatted HTML report"""
        
        html_report = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 20px auto; padding: 20px; }}
        .header {{ background: #0078d4; color: white; padding: 20px; border-radius: 5px; }}
        .health-score {{ font-size: 48px; font-weight: bold; text-align: center; margin: 20px 0; }}
        .score-good {{ color: #107c10; }}
        .score-warning {{ color: #f7630c; }}
        .score-critical {{ color: #d13438; }}
        .section {{ margin: 20px 0; padding: 15px; border-left: 4px solid #0078d4; background: #f5f5f5; }}
        .issue {{ margin: 10px 0; padding: 10px; border-radius: 5px; }}
        .critical {{ background: #fde7e9; border-left: 4px solid #d13438; }}
        .warning {{ background: #fff4ce; border-left: 4px solid #f7630c; }}
        .info {{ background: #e3f2fd; border-left: 4px solid #0078d4; }}
        .metric {{ display: inline-block; margin: 10px 20px 10px 0; }}
        .metric-value {{ font-size: 24px; font-weight: bold; color: #0078d4; }}
        .command {{ background: #2d2d2d; color: #f8f8f8; padding: 10px; border-radius: 5px; 
                    font-family: 'Courier New', monospace; margin: 10px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #0078d4; color: white; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🏥 AKS Health Guardian Report</h1>
        <p>Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
    </div>
    
    <div class="health-score {self._get_score_class(analysis['health_score'])}">
        Health Score: {analysis['health_score']}/100
    </div>
    
    <div class="section">
        <h2>📊 Cluster Overview</h2>
        <div class="metric">
            <div class="metric-value">{cluster_data['pods']['total']}</div>
            <div>Total Pods</div>
        </div>
        <div class="metric">
            <div class="metric-value">{cluster_data['pods']['running']}</div>
            <div>Running</div>
        </div>
        <div class="metric">
            <div class="metric-value" style="color: {'#d13438' if cluster_data['pods']['failed'] > 0 else '#107c10'}">
                {cluster_data['pods']['failed']}
            </div>
            <div>Failed</div>
        </div>
        <div class="metric">
            <div class="metric-value">{cluster_data['pods']['pending']}</div>
            <div>Pending</div>
        </div>
    </div>
    
    <div class="section">
        <h2>📋 Executive Summary</h2>
        <p>{analysis['summary']}</p>
    </div>
    
    <div class="section">
        <h2>⚠️ Issues Detected</h2>
        {self._render_issues(analysis.get('issues', []))}
    </div>
    
    <div class="section">
        <h2>🔮 Predicted Problems</h2>
        {self._render_predictions(analysis.get('predictions', []))}
    </div>
    
    <div class="section">
        <h2>💡 Recommendations</h2>
        {self._render_recommendations(analysis.get('recommendations', []))}
    </div>
    
    <div class="section">
        <h2>📈 Resource Usage</h2>
        {self._render_resource_usage(cluster_data['resource_usage'])}
    </div>
    
    <div class="section">
        <h2>🔔 Recent Events</h2>
        {self._render_events(cluster_data['events'][:15])}
    </div>
    
    <hr style="margin: 30px 0;">
    <p style="text-align: center; color: #666;">
        This report was generated by AKS Health Guardian using Azure OpenAI
    </p>
</body>
</html>
"""
        return html_report
    
    def _get_score_class(self, score):
        if score >= 80:
            return 'score-good'
        elif score >= 60:
            return 'score-warning'
        else:
            return 'score-critical'
    
    def _render_issues(self, issues):
        if not issues:
            return "<p>✅ No major issues detected!</p>"
        
        html = ""
        for issue in issues:
            severity_class = issue['severity'].lower()
            html += f"""
            <div class="issue {severity_class}">
                <strong>{issue['severity'].upper()}: {issue['title']}</strong>
                <p>{issue['description']}</p>
            </div>
            """
        return html
    
    def _render_predictions(self, predictions):
        if not predictions:
            return "<p>No predictions available.</p>"
        
        html = "<ul>"
        for pred in predictions:
            html += f"""
            <li><strong>{pred['timeframe']}:</strong> {pred['issue']} 
                (Probability: {pred['probability']})</li>
            """
        html += "</ul>"
        return html
    
    def _render_recommendations(self, recommendations):
        if not recommendations:
            return "<p>No specific recommendations at this time.</p>"
        
        html = ""
        for rec in recommendations:
            html += f"""
            <div style="margin: 15px 0;">
                <strong>[{rec['priority'].upper()}]</strong> {rec['action']}
                <div class="command">{rec.get('command', 'N/A')}</div>
            </div>
            """
        return html
    
    def _render_resource_usage(self, usage):
        if 'error' in usage:
            return f"<p>Error fetching metrics: {usage['error']}</p>"
        
        html = f"""
        <p>Total CPU Usage: <strong>{usage['total_cpu_usage']:.2f}</strong> millicores</p>
        <p>Total Memory Usage: <strong>{usage['total_memory_usage']:.2f}</strong> Mi</p>
        """
        
        if usage.get('high_cpu_pods'):
            html += "<h4>High CPU Pods:</h4><ul>"
            for pod in usage['high_cpu_pods'][:5]:
                html += f"<li>{pod['namespace']}/{pod['pod']}: {pod['cpu_millicores']}m</li>"
            html += "</ul>"
        
        return html
    
    def _render_events(self, events):
        if not events:
            return "<p>No recent events.</p>"
        
        html = "<table><tr><th>Type</th><th>Reason</th><th>Object</th><th>Message</th></tr>"
        for event in events[:10]:
            html += f"""
            <tr>
                <td>{event['type']}</td>
                <td>{event['reason']}</td>
                <td>{event['object']}</td>
                <td>{event['message'][:100]}...</td>
            </tr>
            """
        html += "</table>"
        return html
    
    def send_email(self, report, recipients):
        """Send report via Azure Logic Apps webhook"""
        import os
        
        webhook_url = os.getenv('LOGIC_APP_WEBHOOK_URL')
        
        if not webhook_url:
            logger.warning("No webhook URL configured, saving report locally")
            with open('/tmp/health_report.html', 'w') as f:
                f.write(report)
            return
        
        payload = {
            "to": ";".join(recipients), # convert list → string
            "subject": f"AKS Health Report - {datetime.utcnow().strftime('%Y-%m-%d')}",
            "body": report
        }
        
        try:
            response = requests.post(webhook_url, json=payload, timeout=10)
            response.raise_for_status()
            logger.info("Report sent successfully!")
        except Exception as e:
            logger.error(f"Failed to send report: {e}")